FROM ubuntu:22.04
LABEL maintainer="AaronPB"

# Install base dependencies and Python 3.10 (default on ubuntu 22.04)
RUN apt-get update && apt-get install -y \
    curl \
    software-properties-common \
    git \
    python3 \
    python3-venv \
    python3-pip

# Install dependencies
## Phidget
RUN curl -fsSL https://www.phidgets.com/downloads/setup_linux | bash &&\
    apt-get install -y libphidget22 libusb-1.0-0

# Install python and python dependencies
COPY requirements.txt requirements.txt

# Use python3 -m pip to install dependencies
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt
