sensor_groups:
  platform_1:
    name: Platform 1
    type: GROUP_PLATFORM
    read: true
    sensor_list:
    - p1_z1
    - p1_z2
    - p1_z3
    - p1_z4
  platform_2:
    name: Platform 2
    type: GROUP_PLATFORM
    read: true
    sensor_list:
    - p2_z1
    - p2_z2
    - p2_z3
    - p2_z4
sensors:
  p1_z1:
    name: P1_LoadCell_Z_1
    type: SENSOR_LOADCELL
    read: true
    connection:
      channel: 0
      serial: 583477
    properties:
      serial_number: Y2131167
      max_weight: 150kg
    calibration:
      slope: 1460645.82
      intercept: -29.233022296826327
  p1_z2:
    name: P1_LoadCell_Z_2
    type: SENSOR_LOADCELL
    read: true
    connection:
      channel: 1
      serial: 583477
    properties:
      serial_number: Y2131169
      max_weight: 150kg
    calibration:
      slope: 1458448.41
      intercept: -29.0028410183748
  p1_z3:
    name: P1_LoadCell_Z_3
    type: SENSOR_LOADCELL
    read: true
    connection:
      channel: 2
      serial: 583477
    properties:
      serial_number: W020822
      max_weight: 150kg
    calibration:
      slope: 1467890.08
      intercept: -27.243367874935444
  p1_z4:
    name: P1_LoadCell_Z_4
    type: SENSOR_LOADCELL
    read: true
    connection:
      channel: 3
      serial: 583477
    read_data: true
    properties:
      serial_number: Y2131168
      max_weight: 150kg
    calibration:
      slope: 1461505.74
      intercept: -38.74350208345997
  p2_z1:
    name: P2_LoadCell_Z_1
    type: SENSOR_LOADCELL
    read: true
    connection:
      channel: 0
      serial: 588569
    properties:
      serial_number: W019737
      max_weight: 150kg
    calibration:
      slope: 1459204.4
      intercept: -45.93060489212014
  p2_z2:
    name: P2_LoadCell_Z_2
    type: SENSOR_LOADCELL
    read: true
    connection:
      channel: 1
      serial: 588569
    properties:
      serial_number: Z1162733
      max_weight: 150kg
    calibration:
      slope: 1459832.02
      intercept: -35.26667409409197
  p2_z3:
    name: P2_LoadCell_Z_3
    type: SENSOR_LOADCELL
    read: true
    connection:
      channel: 2
      serial: 588569
    properties:
      serial_number: Z1162736
      max_weight: 150kg
    calibration:
      slope: 1459933.41
      intercept: -38.56096355307981
  p2_z4:
    name: P2_LoadCell_Z_4
    type: SENSOR_LOADCELL
    read: true
    connection:
      channel: 3
      serial: 588569
    properties:
      serial_number: Z1162741
      max_weight: 150kg
    calibration:
      slope: 1460398.63
      intercept: -40.44425779705251
