name: Docker Image CI for GHCR

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Extract release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/nei-force-platform-ranking:${{ env.RELEASE_VERSION }} .
          docker tag ghcr.io/${{ github.repository_owner }}/nei-force-platform-ranking:${{ env.RELEASE_VERSION }} ghcr.io/${{ github.repository_owner }}/nei-force-platform-ranking:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/nei-force-platform-ranking:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/nei-force-platform-ranking:latest